EduHomeProcekt(Edmin)/Eduhome/Models/Social.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Models
{
    public class Social
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(30,ErrorMessage ="30-dan sora yazmagi dusunme haa")]
        public string Name { get; set; }
        [MaxLength(100, ErrorMessage = "100-dan sora yazmagi dusunme haa")]
        public string Icon { get; set; }
        [MaxLength(100, ErrorMessage = "100-dan sora yazmagi dusunme haa")]
        public string Link { get; set; }
    }
}

EduHomeProcekt(Edmin)/Eduhome/Areas/Admin/Controllers/SocialController.cs
using Eduhome.EduHomeDbContext;
using Eduhome.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SocialController : Controller
    {
        private readonly EduHomeDb _context;
        public SocialController(EduHomeDb context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Social> model = _context.Socials.ToList();
            return View(model);
        }

        #region Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Social model)
        {
            if (ModelState.IsValid)
            {
                _context.Socials.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Menim errorum");
            return View(model);
        }
        #endregion

        #region Update

        public IActionResult Update(int id)
        {
            return View(_context.Socials.Find(id));
        }

        [HttpPost]
        public IActionResult Update(Social model)
        {
            if (ModelState.IsValid)
            {
                _context.Socials.Update(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Menim errorum");
            return View(model);
        }
        #endregion

        #region Delete

        public IActionResult Delete(int? id)
        {
            //if (id == null)
            //{
            //    HttpContext.Session.SetString("NullIdError", "Id can not be null");
            //    return RedirectToAction("Index");
            //}
            Social social = _context.Socials.Find(id);
            _context.Socials.Remove(social);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
        #endregion
    }
}

EduHomeProcekt(Edmin)/Eduhome/Areas/Admin/Views/Social/Create.cshtml
@model Social
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">        
        <div class="col-lg-6">
            <form style="margin-left: 100px;" asp-area="Admin" asp-controller="Social" asp-action="Create" method="post">
                <div asp-validation-summary="All" style="color:red;"></div>
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label">Name</label>
                    <input class="form-control"asp-for="@Model.Name">
                    <br />
                    <span asp-validation-for="@Model.Name" style="color:red;"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="@Model.Icon" class="form-label">Icon</label>
                    <input class="form-control" asp-for="@Model.Icon">
                    <br />
                    <span asp-validation-for="@Model.Icon" style="color:red;"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.Link" class="form-label">Link</label>
                    <input class="form-control" asp-for="@Model.Link">
                    <br />
                    <span asp-validation-for="@Model.Link" style="color:red;"></span>
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
                <a asp-area="Admin" asp-controller="Social" asp-action="Index">Back to list</a>
            </form>
        </div>
    </div>
</div>

EduHomeProcekt(Edmin)/Eduhome/Areas/Admin/Views/Social/Index.cshtml
@model List<Social>
@*@inject IHttpContextAccessor HttpContextAccessor*@
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container" style="width: 100%;">
    <div class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary mb-3" asp-area="Admin" asp-controller="Social" asp-action="Create">Create</a>
        </div>
        @*<div class="col-lg-12">
            @if (HttpContextAccessor.HttpContext.Session.GetString("NullIdError")!="null")
            {
                <div class="alert alert-danger">
                    @HttpContextAccessor.HttpContext.Session.GetString("NullIdError")
                </div>

                HttpContextAccessor.HttpContext.Session.SetString("NullIdError", "null");
            }
        </div>*@
        <hr />
        <div class="col-lg-12 mt-5">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Icon</th>
                        <th scope="col">Link</th>
                        <th scope="col"></th>
                    </tr>   
                </thead>
                <tbody>
                    @{ int i = 0;
                        foreach (var item in Model)
                        {
                            i++;
                            <tr>
                                <th scope="row">@i</th>
                                <td>@item.Name</td>
                                <td>@item.Icon</td>
                                <td>@item.Link</td>
                                <td>
                                    <a class="btn btn-success" asp-area="Admin" asp-controller="Social" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                    <a class="btn btn-danger" asp-area="Admin" asp-controller="Social" asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Deqiq silmek isteyirsen Qaqaa(Bax silirem haaaaa)?')">Delete</a>
                                </td>

                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

EduHomeProcekt(Edmin)/Eduhome/Areas/Admin/Views/Social/Update.cshtml
@model Social
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <form style="margin-left: 100px;" asp-area="Admin" asp-controller="Social" asp-action="Update" method="post">
                <div asp-validation-summary="All" style="color:red;"></div>
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label">Name</label>
                    <input class="form-control" asp-for="@Model.Name">
                    <br />
                    <span asp-validation-for="@Model.Name" style="color:red;"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="@Model.Icon" class="form-label">Icon</label>
                    <input class="form-control" asp-for="@Model.Icon">
                    <br />
                    <span asp-validation-for="@Model.Icon" style="color:red;"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model.Link" class="form-label">Link</label>
                    <input class="form-control" asp-for="@Model.Link">
                    <br />
                    <span asp-validation-for="@Model.Link" style="color:red;"></span>
                </div>

                <input class="form-control" type="hidden" asp-for="@Model.Id">

                <button type="submit" class="btn btn-primary">Update</button>
                <a asp-area="Admin" asp-controller="Social" asp-action="Index">Back to list</a>
            </form>
        </div>
    </div>
</div>