EduHomeProcekt(Edmin)/Eduhome/Controllers/CourseController.cs
using Eduhome.EduHomeDbContext;
using Eduhome.Models;
using Eduhome.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Controllers
{
    public class CourseController : Controller
    {
        private readonly EduHomeDb _context;
        public CourseController(EduHomeDb context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            HomeModel homemodels = new HomeModel();

            Setting setting = _context.Settings.FirstOrDefault();
            Subscribe subscribe = _context.Subscribes.FirstOrDefault();
            List<Social> socials = _context.Socials.ToList();
            Banner banner = _context.Banners.FirstOrDefault();
            List<Course> courses = _context.Courses.ToList();

            homemodels.Banner = banner;
            homemodels.Courses = courses;
            homemodels.Setting = setting;
            homemodels.Subscribe = subscribe;
            homemodels.Socials = socials;
            return View(homemodels);
        }
    }
}

EduHomeProcekt(Edmin)/Eduhome/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edmin</title>
    <link type="text/css" href="~/Areas/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="~/Areas/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link type="text/css" href="~/Areas/css/theme.css" rel="stylesheet">
    <link type="text/css" href="~/Areas/images/icons/css/font-awesome.css" rel="stylesheet">
    <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
          rel='stylesheet'>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                    <i class="icon-reorder shaded"></i>
                </a>
                <a class="brand" asp-area="Admin" asp-controller="Home" asp-action="Index">Edmin </a>
                <div class="nav-collapse collapse navbar-inverse-collapse">
                    <ul class="nav nav-icons">
                        <li class="active"><a href="#"><i class="icon-envelope"></i></a></li>
                        <li><a href="#"><i class="icon-eye-open"></i></a></li>
                        <li><a href="#"><i class="icon-bar-chart"></i></a></li>
                    </ul>
                    <form class="navbar-search pull-left input-append" action="#">
                        <input type="text" class="span3">
                        <button class="btn" type="button">
                            <i class="icon-search"></i>
                        </button>
                    </form>
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Dropdown
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Item No. 1</a></li>
                                <li><a href="#">Don't Click</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Example Header</li>
                                <li><a href="#">A Separated link</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Support </a></li>
                        <li class="nav-user dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Areas/images/user.png" class="nav-avatar" />
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Your Profile</a></li>
                                <li><a href="#">Edit Profile</a></li>
                                <li><a href="#">Account Settings</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.nav-collapse -->
            </div>
        </div>
        <!-- /navbar-inner -->
    </div>
    <!-- /navbar -->
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <div class="sidebar">
                        <ul class="widget widget-menu unstyled">
                            <li class="active">
                                <a href="index.html">
                                    <i class="menu-icon icon-dashboard"></i>Dashboard
                                </a>
                            </li>
                            <li>
                                <a href="activity.html"><i class="menu-icon icon-bullhorn"></i>News Feed </a>
                            </li>
                            <li>
                                <a href="message.html">
                                    <i class="menu-icon icon-inbox"></i>Inbox <b class="label green pull-right">
                                        11
                                    </b>
                                </a>
                            </li>
                            <li>
                                <a href="task.html">
                                    <i class="menu-icon icon-tasks"></i>Tasks <b class="label orange pull-right">
                                        19
                                    </b>
                                </a>
                            </li>
                        </ul>
                        <!--/.widget-nav-->


                        <ul class="widget widget-menu unstyled">
                            <li><a href="ui-button-icon.html"><i class="menu-icon icon-bold"></i> Buttons </a></li>
                            <li><a href="ui-typography.html"><i class="menu-icon icon-book"></i>Typography </a></li>
                            <li><a href="form.html"><i class="menu-icon icon-paste"></i>Forms </a></li>
                            <li><a href="table.html"><i class="menu-icon icon-table"></i>Tables </a></li>
                            <li><a href="charts.html"><i class="menu-icon icon-bar-chart"></i>Charts </a></li>
                        </ul>
                        <!--/.widget-nav-->
                        <ul class="widget widget-menu unstyled">
                            <li>
                                <a class="collapsed" data-toggle="collapse" href="#togglePages">
                                    <i class="menu-icon icon-cog">
                                    </i><i class="icon-chevron-down pull-right"></i><i class="icon-chevron-up pull-right">
                                    </i>More Pages
                                </a>
                                <ul id="togglePages" class="collapse unstyled">
                                    <li><a asp-area="Admin" asp-controller="Social" asp-action="Index"><i class="icon-inbox"></i>Social </a></li>
                                    <li><a asp-area="Admin" asp-controller="Course" asp-action="Index"><i class="icon-inbox"></i>Course </a></li>
                                </ul>
                            </li>
                            <li><a href="#"><i class="menu-icon icon-signout"></i>Logout </a></li>
                        </ul>
                    </div>
                    <!--/.sidebar-->
                </div>
                <!--/.span3-->
                <span class="span9">
                    @RenderBody()

                </span>



            </div>
        </div>
        <!--/.container-->
    </div>
    <!--/.wrapper-->
    <div class="footer">
        <div class="container">
            <b class="copyright">&copy; 2014 Edmin - EGrappler.com </b>All rights reserved.
        </div>
    </div>
    <script src="~/Areas/scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="~/Areas/scripts/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
    <script src="~/Areas/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Areas/scripts/flot/jquery.flot.js" type="text/javascript"></script>
    <script src="~/Areas/scripts/flot/jquery.flot.resize.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/Areas/scripts/datatables/jquery.dataTables.js" type="text/javascript"></script>
    <script src="~/Areas/scripts/common.js" type="text/javascript"></script>
    <script src="~/js/script.js"></script>
</body>
</html>